<?php
/**
 * Product Barcode Generator & Printing
 */

require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/functions.php';

requireLogin();

$product_id = isset($_GET['id']) ? (int)$_GET['id'] : null;
if (!$product_id) redirect('index.php');

$stmt = $pdo->prepare("SELECT * FROM products WHERE id = ?" . (!isAdmin() ? " AND branch_id = " . (int)$_SESSION['branch_id'] : ""));
$stmt->execute([$product_id]);
$product = $stmt->fetch();

if (!$product || empty($product['barcode'])) {
    flashMessage('danger', 'Product or Barcode not found.');
    redirect('index.php');
}

$pageTitle = 'Print Barcode';
$breadcrumb = '<a href="' . BASE_URL . '/modules/products/index.php">Products</a><span class="sep"><i class="fas fa-chevron-right"></i></span><span class="current">Barcode</span>';

include_once __DIR__ . '/../../includes/header.php';
?>

<style>
    @media print {
        body * { visibility: hidden; }
        .print-area, .print-area * { visibility: visible; }
        .print-area { position: absolute; left: 0; top: 0; width: 100%; }
        .no-print { display: none !important; }
        
        .barcode-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10px;
        }
        .barcode-item {
            border: 1px solid #eee;
            padding: 10px;
            text-align: center;
            page-break-inside: avoid;
        }
    }
    
    .barcode-preview-card {
        background: white;
        padding: 30px;
        border-radius: var(--radius-lg);
        text-align: center;
        border: 1px solid var(--border);
    }
</style>

<div class="row justify-content-center no-print">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Barcode Preview: <?php echo sanitize($product['name']); ?></h3>
                <a href="index.php" class="btn btn-outline btn-sm">Back</a>
            </div>
            
            <div class="barcode-preview-card mt-4">
                <svg id="barcodeCanvas"></svg>
                <div class="mt-3">
                    <h4 class="mb-1"><?php echo sanitize($product['name']); ?></h4>
                    <div class="text-muted fs-13">SKU: <?php echo sanitize($product['sku']); ?></div>
                    <div class="fw-700 fs-18 mt-2"><?php echo formatCurrency($product['selling_price']); ?></div>
                </div>
            </div>

            <div class="form-card mt-4">
                <form id="printForm">
                    <div class="form-row">
                        <div class="form-group">
                            <label class="form-label">Number of Labels</label>
                            <input type="number" id="labelCount" class="form-control" value="1" min="1" max="100">
                        </div>
                        <div class="form-group">
                            <label class="form-label">Paper Format</label>
                            <select id="paperFormat" class="form-control">
                                <option value="a4">A4 Sheet (3 columns)</option>
                                <option value="thermal">Thermal (Single)</option>
                            </select>
                        </div>
                    </div>
                    <button type="button" onclick="window.print()" class="btn btn-primary w-100 mt-4">
                        <i class="fas fa-print"></i> Print Labels
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Print Area (Hidden in UI, Visible in Print) -->
<div class="print-area d-none">
    <div id="printGrid" class="barcode-grid">
        <!-- Generated by JS -->
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3/dist/JsBarcode.all.min.js"></script>
<script>
    const barcodeVal = "<?php echo $product['barcode']; ?>";
    const prodName = "<?php echo addslashes($product['name']); ?>";
    const prodPrice = "<?php echo formatCurrency($product['selling_price']); ?>";

    function renderBarcode() {
        JsBarcode("#barcodeCanvas", barcodeVal, {
            format: "CODE128",
            width: 2,
            height: 80,
            displayValue: true
        });
    }

    window.onbeforeprint = function() {
        const count = document.getElementById('labelCount').value;
        const grid = document.getElementById('printGrid');
        grid.innerHTML = '';
        
        for (let i = 0; i < count; i++) {
            const item = document.createElement('div');
            item.className = 'barcode-item';
            item.innerHTML = `
                <div style="font-size: 10px; font-weight: bold; margin-bottom: 2px;">${prodName}</div>
                <svg class="barcode-render-${i}"></svg>
                <div style="font-size: 12px; font-weight: bold; margin-top: 2px;">${prodPrice}</div>
            `;
            grid.appendChild(item);
            
            JsBarcode(`.barcode-render-${i}`, barcodeVal, {
                format: "CODE128",
                width: 1.2,
                height: 40,
                displayValue: true,
                fontSize: 10
            });
        }
        document.querySelector('.print-area').classList.remove('d-none');
    };

    window.onafterprint = function() {
        document.querySelector('.print-area').classList.add('d-none');
    };

    renderBarcode();
</script>

<?php include_once __DIR__ . '/../../includes/footer.php'; ?>
